#ifndef TATCOREPROCESSBACKENDDEBUGSWITCHER_H
#define TATCOREPROCESSBACKENDDEBUGSWITCHER_H
const bool DEBUGLOADSTUINFO=true;
const bool DEBUGSHOWSTUINFO=false;
const bool DEBUGMODIFYSTUINFO=false;
const bool DEBUGLOADFS=false;
const bool DEBUGPROBECLASS=false;
const bool DEBUGLOADSETTINGS=false;
const bool DEBUGSORTLIST=true;
#endif // TATCOREPROCESSBACKENDDEBUGSWITCHER_H
